### ISSUE TITLE
pip_repository fails if python3-distutils is not installed on build system

### ISSUE THREAD

**Issue by asv** [dillon-giacoppo/rules_python_external#37]
`distutils` package for `python3` may not always be installed on the build system. For example, this happens in my Debian 10. This causes target pip_repository to return an error:

```
INFO: Call stack for the definition of repository 'sphinx_deps' which is a pip_repository (rule definition at /home/asmirnov/.cache/bazel/_bazel_asmirnov/21e836bd6a9d91d4ee2184dc83b17371/exte
rnal/rules_python_external/defs.bzl:46:18):                                                                                                                                                    
 - /home/asmirnov/.cache/bazel/_bazel_asmirnov/21e836bd6a9d91d4ee2184dc83b17371/external/rules_python_external/defs.bzl:59:5                                                                   
 - /home/asmirnov/.cache/bazel/_bazel_asmirnov/21e836bd6a9d91d4ee2184dc83b17371/external/rules_python_external/defs.bzl:59:5                                                                   
 - /home/asmirnov/devel/scm.infinet.ru/nms/next-master/WORKSPACE:243:1                                                                                                                         
ERROR: An error occurred during the fetch of repository 'sphinx_deps':                                                                                                                         
   rules_python_external failed:  (Traceback (most recent call last):                                                                                                                          
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main                                                                                                                         
    "__main__", mod_spec)                                                                                                                                                                      
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code                                                                                                                                    
    exec(code, run_globals)                                                                                                                                                                    
  File "/home/asmirnov/.cache/bazel/_bazel_asmirnov/21e836bd6a9d91d4ee2184dc83b17371/external/pypi__pip/pip/__main__.py", line 16, in <module>                                                 
    from pip._internal.main import main as _main  # isort:skip # noqa                                                                                                                          
  File "/home/asmirnov/.cache/bazel/_bazel_asmirnov/21e836bd6a9d91d4ee2184dc83b17371/external/pypi__pip/pip/_internal/main.py", line 13, in <module>                                           
    from pip._internal.cli.autocompletion import autocomplete                                                                                                                                  
  File "/home/asmirnov/.cache/bazel/_bazel_asmirnov/21e836bd6a9d91d4ee2184dc83b17371/external/pypi__pip/pip/_internal/cli/autocompletion.py", line 11, in <module>                             
    from pip._internal.cli.main_parser import create_main_parser                                                                                                                               
  File "/home/asmirnov/.cache/bazel/_bazel_asmirnov/21e836bd6a9d91d4ee2184dc83b17371/external/pypi__pip/pip/_internal/cli/main_parser.py", line 7, in <module>                                 
    from pip._internal.cli import cmdoptions                                                                                                                                                   
  File "/home/asmirnov/.cache/bazel/_bazel_asmirnov/21e836bd6a9d91d4ee2184dc83b17371/external/pypi__pip/pip/_internal/cli/cmdoptions.py", line 19, in <module>                                 
    from distutils.util import strtobool                                                                                                                                                       
ModuleNotFoundError: No module named 'distutils.util'                                                                                                                                          
Traceback (most recent call last):                                                                                                                                                             
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main                                                                                                                         
    "__main__", mod_spec)                                                                                                                                                                      
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code                                                                                                                                    
    exec(code, run_globals)                                                                                                                                                                    
  File "/home/asmirnov/.cache/bazel/_bazel_asmirnov/21e836bd6a9d91d4ee2184dc83b17371/external/rules_python_external/extract_wheels/__main__.py", line 5, in <module>                           
    extract_wheels.main()                                                                                                                                                                      
  File "/home/asmirnov/.cache/bazel/_bazel_asmirnov/21e836bd6a9d91d4ee2184dc83b17371/external/rules_python_external/extract_wheels/__init__.py", line 70, in main                              
    [sys.executable, "-m", "pip", "wheel", "-r", args.requirements]                                                                                                                            
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output                                                                                                                           
    **kwargs).stdout                                                                                                                                                                           
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'wheel', '-r', '/home/asmirnov/devel/scm.infinet.ru/nms/next-master/docs/requirements.txt']' returned non-zero exit s
tatus 1.
)
```
Maybe should add it  as depends on rules_python_external or describe clarify prerequisites.

**Comment by dillon-giacoppo** [comment]
IIUC, `distutils.util` is not a `pip` installable package but rather is something that comes with the stdlib of Python. It looks like Debian and Ubuntu have decided that distutils should be optional. It looks like this issue has been raised with `get-pip` and summarised by https://github.com/pypa/get-pip/issues/43#issuecomment-596232045.

The workaround as noted on that ticket is to install the full Python stdlib with:

```sh
apt install python3-dev  # or `apt install python3-distutils`
```

Whilst adding a comment in the README is trivial, I don't think we should be writing and maintaining Python installation instructions for each distro. Whilst I agree its an annoying caveat that Debian and Ubuntu don't contain the full stdlib, a dependency on the stdlib of Python is not unreasonable and should not have to be explicitly declared.

IMO, we should close this ticket, but it will serve as a reference for anyone who stumbles into this in the future.
