### ISSUE TITLE
setuptools 50 bug shows up inside the sandbox

### ISSUE THREAD

**Issue by jasonh-logic2020** [dillon-giacoppo/rules_python_external#57]
Hello.

[This bug](https://github.com/pypa/setuptools/issues/2353) occurs while processing requirements.txt if any of the affected libraries are in the file.

Builds of existing, unmodified repos work as before but any update to requirements.txt seems to trigger bazel to download a new (i.e. version 50) setuptools and start failing. The box I build on has setuptools 40 so this is something which is happening inside the bazel sandbox. I use both rules_python 0.0.1 and a commit-locked version of rules_python_external from March. 

I see what looks like earlier setuptools versions in your code (and in rules_python's internal requirements.txt) so I'm not sure why the bug in version 50 is showing up.

I assume I should be filing here rather than at rules_python because we use rules_python_external's pip_install rule to process our requirements files.

Any workarounds or fixes welcome. Please let me know if you need more information

Thanks.

**Comment by dillon-giacoppo** [comment]
r_p_e depends on setuptools but we use a pinned version so I don't really understand how/why you are getting v50. Is setup tool a requirement in your project?

Can you please post full stack traces of the error you get and a minimal reproduction.

**Comment by jasonh-logic2020** [comment]
Thanks for your response. Here is our setup and the logs.

Here is the relevant WORKSPACE section

```
git_repository(
    name = "rules_python",
    remote = "https://github.com/bazelbuild/rules_python.git",
    commit = "38f86fb55b698c51e8510c807489c9f4e047480e",
)

load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()
rules_python_external_version = "41777ee36c971e20a5712875c95236731b05d068"

http_archive(
    name = "rules_python_external",
    sha256 = "cbf346ea16ad1de6259e056bb9a254f0b12acd0e64171f9fe1804205203b8355", # Fill in with correct sha256 of your COMMIT_SHA version
    strip_prefix = "rules_python_external-41777ee36c971e20a5712875c95236731b05d068".format(version = rules_python_external_version),
    url = "https://github.com/dillon-giacoppo/rules_python_external/archive/41777ee36c971e20a5712875c95236731b05d068.zip".format(version = rules_python_external_version),
)

# Install the rule dependencies
load("@rules_python_external//:repositories.bzl", "rules_python_external_dependencies")
rules_python_external_dependencies()

load("@rules_python_external//:defs.bzl", "pip_install")
pip_install(
    name = "lib_interceptor",
    requirements = "//lib/interceptor:requirements.txt",
)

load("@rules_python_external//:defs.bzl", "pip_install")
pip_install(
    name = "modelbox_run_dependencies",
    requirements = "//lib/modelbox:requirements.txt",
)

```
As you see, we install two requirement.txt files. `//lib/interceptor:requirements.txt` contains
```
setuptools==40.8.0 \
    --hash=sha256:e8496c0079f3ac30052ffe69b679bd876c5265686127a3159cfa415669b7f9ab
```

and  `//lib/interceptor:requirements.txt` contains
```
setuptools==45.2.0 \
   --hash=sha256:316484eebff54cc18f322dea09ed031b7e3eb00811b19dcedb09bc09bba7d93d 
```

These have been building correctly for months. As of the date of the linked bug, when we try to add libraries, we get the symptoms of the bug. Here are the logs from that build (apologies for the length):

```
+ bazel build //main_[project name redacted]_run:image
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: target //main_[project name redacted]_run:image (1 packages loaded, 0 targets configured)
Analyzing: target //main_[project name redacted]_run:image (27 packages loaded, 114 targets configured)
Analyzing: target //main_[project name redacted]_run:image (44 packages loaded, 405 targets configured)
Analyzing: target //main_[project name redacted]_run:image (70 packages loaded, 6935 targets configured)
Analyzing: target //main_[project name redacted]_run:image (89 packages loaded, 7054 targets configured)
Analyzing: target //main_[project name redacted]_run:image (89 packages loaded, 7054 targets configured)
INFO: Repository [project name redacted]_run_dependencies instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule pip_repository defined at:
  /var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/rules_python_external/defs.bzl:41:18: in <toplevel>
Analyzing: target //main_[project name redacted]_run:image (89 packages loaded, 7054 targets configured)
ERROR: An error occurred during the fetch of repository '[project name redacted]_run_dependencies':
   rules_python_external failed:  (ERROR: Exception:
Traceback (most recent call last):
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/commands/wheel.py", line 158, in run
    resolver.resolve(requirement_set)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/operations/prepare.py", line 224, in prepare_linked_requirement
    req, self.req_tracker, finder, self.build_isolation,
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/distributions/source/legacy.py", line 37, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/distributions/source/legacy.py", line 90, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_vendor/pep517/wrappers.py", line 152, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_vendor/pep517/wrappers.py", line 255, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_vendor/pep517/_in_process.py", line 63, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 5, in <module>
    import distutils.core
  File "/tmp/pip-build-env-_ig9bio1/overlay/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 83, in create_module
    return importlib.import_module('._distutils', 'setuptools')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'setuptools._distutils'

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/rules_python_external/src/__main__.py", line 38, in <module>
    whl.main()
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/rules_python_external/src/extract_wheels.py", line 109, in main
    [sys.executable, "-m", "pip", "wheel", "-r", args.requirements]
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'wheel', '-r', '/var/lib/jenkins/workspace/MOB_[Project Name Redacted]_Run_dev/lib/[project name redacted]/requirements.txt']' returned non-zero exit status 2.
)
ERROR: /var/lib/jenkins/workspace/MOB_[Project Name Redacted]_Run_dev/main_[project name redacted]_run/BUILD:35:1: //main_[project name redacted]_run:image.binary depends on //lib/[project name redacted]:[project name redacted]_py in repository @ which failed to fetch. no such package '@[project name redacted]_run_dependencies//': rules_python_external failed:  (ERROR: Exception:
Traceback (most recent call last):
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/commands/wheel.py", line 158, in run
    resolver.resolve(requirement_set)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/operations/prepare.py", line 224, in prepare_linked_requirement
    req, self.req_tracker, finder, self.build_isolation,
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/distributions/source/legacy.py", line 37, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/distributions/source/legacy.py", line 90, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_vendor/pep517/wrappers.py", line 152, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_vendor/pep517/wrappers.py", line 255, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_vendor/pep517/_in_process.py", line 63, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 5, in <module>
    import distutils.core
  File "/tmp/pip-build-env-_ig9bio1/overlay/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 83, in create_module
    return importlib.import_module('._distutils', 'setuptools')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'setuptools._distutils'

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/rules_python_external/src/__main__.py", line 38, in <module>
    whl.main()
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/rules_python_external/src/extract_wheels.py", line 109, in main
    [sys.executable, "-m", "pip", "wheel", "-r", args.requirements]
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'wheel', '-r', '/var/lib/jenkins/workspace/MOB_[Project Name Redacted]_Run_dev/lib/[project name redacted]/requirements.txt']' returned non-zero exit status 2.
)
ERROR: Analysis of target '//main_[project name redacted]_run:image' failed; build aborted: no such package '@[project name redacted]_run_dependencies//': rules_python_external failed:  (ERROR: Exception:
Traceback (most recent call last):
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/commands/wheel.py", line 158, in run
    resolver.resolve(requirement_set)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/operations/prepare.py", line 224, in prepare_linked_requirement
    req, self.req_tracker, finder, self.build_isolation,
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/distributions/source/legacy.py", line 37, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_internal/distributions/source/legacy.py", line 90, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_vendor/pep517/wrappers.py", line 152, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_vendor/pep517/wrappers.py", line 255, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_vendor/pep517/_in_process.py", line 63, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 5, in <module>
    import distutils.core
  File "/tmp/pip-build-env-_ig9bio1/overlay/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 83, in create_module
    return importlib.import_module('._distutils', 'setuptools')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'setuptools._distutils'

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/rules_python_external/src/__main__.py", line 38, in <module>
    whl.main()
  File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/rules_python_external/src/extract_wheels.py", line 109, in main
    [sys.executable, "-m", "pip", "wheel", "-r", args.requirements]
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'wheel', '-r', '/var/lib/jenkins/workspace/MOB_[Project Name Redacted]_Run_dev/lib/[project name redacted]/requirements.txt']' returned non-zero exit status 2.
)
INFO: Elapsed time: 39.518s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (89 packages loaded, 7054 targets configured)
FAILED: Build did NOT complete successfully (89 packages loaded, 7054 targets configured)
```
Please let mer know if you need more information.

**Comment by thundergolfer** [comment]
> r_p_e depends on setuptools but we use a pinned version so I don't really understand how/why you are getting v50.

If we look at this portion of the error just posted: 

```
 File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/953a94c211bd78097643cebba9db2ce1/external/pypi__pip/pip/_vendor/pep517/_in_process.py", line 63, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 5, in <module>
    import distutils.core
```

We see that:

1. We're clearly executing vendored `pip`
2. Vendored pip runs `obj = import_module(mod_path)`
3. We've 'escaped' and are now running system code `"/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module` leads to `"/usr/local/lib/python3.7/dist-packages/setuptools/`
4. We hit the broken line in the system `setuptools`: `"/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 5,`

I think if @jasonh-logic2020 gets the `__version__` of `/usr/local/lib/python3.7/dist-packages/setuptools` it'd be setuptools 50.

**Comment by jasonh-logic2020** [comment]
That bug has been closed and further investigation has revealed [this new reading of the root cause](https://github.com/pypa/pip/issues/6264#issuecomment-685230919). I think we can agree that neither of us is leaking versions and that the underlying tools were broken. 

A [fix](https://github.com/equinor/latigo/pull/119) is working its way through the approval process so hopefully we can all upgrade soon.

I'm closing this but thank you for taking the time to investigate.

**Comment by thundergolfer** [comment]
>  The .pth file runs even though another version of setuptools is before it in the module search path

Oof. Right, that would explain what I called the 'escaping'. Agree that there's probably nothing we could've done about this.
